# Generated by Django 6.0.5 on 2026-05-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('curator', 'Куратор'), ('student', 'Студент')], default='curator', max_length=20, verbose_name='Роль'),
        ),
    ]
