# Generated by Django 6.0.5 on 2026-05-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
        ('mainPage', '0005_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='mainPage.group', verbose_name='Ведет группы'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='mainPage.subject', verbose_name='Ведет предметы'),
        ),
        migrations.AddField(
            model_name='user',
            name='curated_groups',
            field=models.ManyToManyField(blank=True, related_name='curators', to='mainPage.group', verbose_name='Курируемые группы'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_users', to='mainPage.group', verbose_name='Группа (для студента)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('curator', 'Куратор'), ('student', 'Студент')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
