# Generated by Django 6.0.4 on 2026-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_distance',
            field=models.BooleanField(default=False, verbose_name='Дистанционное обучение'),
        ),
    ]
