# Generated by Django 6.0.4 on 2026-05-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_alter_grade_options_subject_name_alter_grade_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='default', max_length=50, unique=True, verbose_name='Предмет (английское название)'),
        ),
    ]
